# Generated by Django 5.2.17 on 2026-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва')),
                ('edrpou', models.CharField(max_length=8, unique=True, verbose_name='ЄДРПОУ')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ІПН')),
                ('address', models.CharField(max_length=500, verbose_name='адреса')),
                ('bank_details', models.TextField(blank=True, verbose_name='банківські реквізити')),
                ('director', models.CharField(max_length=255, verbose_name='директор')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'компанія',
                'verbose_name_plural': 'профіль компанії',
            },
        ),
    ]
