# Generated by Django 5.2.17 on 2026-09-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва')),
                ('edrpou', models.CharField(max_length=8, unique=True, verbose_name='ЄДРПОУ')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ІПН')),
                ('address', models.CharField(max_length=500, verbose_name='адреса')),
                ('bank_details', models.TextField(blank=True, verbose_name='банківські реквізити')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='директор')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='номер договору')),
                ('date', models.DateField(verbose_name='дата договору')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='partners.counterparty', verbose_name='контрагент-замовник')),
            ],
            options={
                'verbose_name': 'договір',
                'verbose_name_plural': 'договори',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('counterparty', 'number'), name='uniq_contract_number_per_counterparty')],
            },
        ),
    ]
