# Generated by Django 5.2.17 on 2026-09-09 13:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='edrpou',
            field=models.CharField(max_length=8, unique=True, validators=[core.validators.validate_edrpou], verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.CharField(blank=True, max_length=12, validators=[core.validators.validate_inn], verbose_name='ІПН'),
        ),
    ]
