# Generated by Django 5.2.17 on 2026-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_counterparty_edrpou_alter_counterparty_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Залиште порожнім, якщо договір безстроковий.', null=True, verbose_name='діє до'),
        ),
    ]
