# Generated by Django 5.2.17 on 2026-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('license_number', models.CharField(max_length=32, unique=True, verbose_name='номер посвідчення')),
                ('license_expiry', models.DateField(verbose_name='посвідчення дійсне до')),
            ],
            options={
                'verbose_name': 'водій',
                'verbose_name_plural': 'водії',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(max_length=100, verbose_name='марка / модель')),
                ('plate_number', models.CharField(max_length=16, unique=True, verbose_name='державний номер')),
            ],
            options={
                'verbose_name': 'причіп',
                'verbose_name_plural': 'причепи',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(max_length=100, verbose_name='марка / модель')),
                ('plate_number', models.CharField(max_length=16, unique=True, verbose_name='державний номер')),
                ('vehicle_type', models.CharField(default='вантажний', max_length=50, verbose_name='тип')),
                ('capacity_t', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='вантажопідйомність, т')),
                ('length_m', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='довжина, м')),
                ('width_m', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='ширина, м')),
                ('height_m', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='висота, м')),
                ('inspection_expiry', models.DateField(verbose_name='техогляд дійсний до')),
            ],
            options={
                'verbose_name': 'автомобіль',
                'verbose_name_plural': 'автомобілі',
                'ordering': ['plate_number'],
            },
        ),
    ]
