# Generated by Django 5.2.17 on 2026-09-09 13:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='plate_number',
            field=models.CharField(max_length=16, unique=True, validators=[core.validators.validate_plate_number], verbose_name='державний номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=16, unique=True, validators=[core.validators.validate_plate_number], verbose_name='державний номер'),
        ),
    ]
