# Generated by Django 5.2.17 on 2026-09-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='номер акту')),
                ('date', models.DateField(verbose_name='дата складання')),
                ('amount_no_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума без ПДВ, грн')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ПДВ 20%, грн')),
                ('amount_with_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума з ПДВ, грн')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='partners.contract', verbose_name='договір')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts_as_customer', to='partners.counterparty', verbose_name='замовник')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts_as_executor', to='core.company', verbose_name='виконавець')),
            ],
            options={
                'verbose_name': 'акт здачі-прийняття робіт',
                'verbose_name_plural': 'акти здачі-прийняття робіт',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='опис послуги')),
                ('weight_t', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='вага, т')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума, грн')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.act', verbose_name='акт')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_lines', to='trips.trip', verbose_name='рейс')),
            ],
            options={
                'verbose_name': 'рядок акту',
                'verbose_name_plural': 'рядки акту',
            },
        ),
        migrations.CreateModel(
            name='TTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='номер ТТН')),
                ('date', models.DateField(verbose_name='дата складання')),
                ('place', models.CharField(max_length=255, verbose_name='місце складання')),
                ('accompanying_docs', models.CharField(blank=True, max_length=500, verbose_name='супровідні документи на вантаж')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ttn', to='trips.trip', verbose_name='рейс')),
            ],
            options={
                'verbose_name': 'ТТН',
                'verbose_name_plural': 'ТТН',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CargoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='найменування вантажу')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='одиниця виміру')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='кількість місць')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ціна без ПДВ за одиницю, грн')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума з ПДВ, грн')),
                ('packaging', models.CharField(blank=True, max_length=100, verbose_name='вид пакування')),
                ('ttn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_lines', to='documents.ttn', verbose_name='ТТН')),
            ],
            options={
                'verbose_name': 'рядок вантажу ТТН',
                'verbose_name_plural': 'рядки вантажу ТТН',
            },
        ),
    ]
