# Generated by Django 5.2.17 on 2026-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoline',
            name='weight_t',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='маса брутто рядка, т'),
        ),
    ]
