# Generated by Django 5.2.17 on 2026-09-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата рейсу')),
                ('loading_address', models.CharField(max_length=500, verbose_name='пункт навантаження')),
                ('unloading_address', models.CharField(max_length=500, verbose_name='пункт розвантаження')),
                ('route_text', models.CharField(blank=True, max_length=500, verbose_name='маршрут')),
                ('weight_t', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='маса брутто, т')),
                ('amount_no_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума без ПДВ, грн')),
                ('status', models.CharField(choices=[('draft', 'чернетка'), ('confirmed', 'підтверджено')], default='draft', max_length=16, verbose_name='статус')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_carrier', to='partners.counterparty', verbose_name='перевізник')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='partners.contract', verbose_name='договір')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.driver', verbose_name='водій')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_receiver', to='partners.counterparty', verbose_name='вантажоодержувач')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_sender', to='partners.counterparty', verbose_name='вантажовідправник')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.trailer', verbose_name='причіп')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle', verbose_name='автомобіль')),
            ],
            options={
                'verbose_name': 'рейс',
                'verbose_name_plural': 'рейси',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
