# Generated by Django 5.2.17 on 2026-09-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'чернетка'), ('confirmed', 'підтверджено')], max_length=16, verbose_name='з статусу')),
                ('to_status', models.CharField(choices=[('draft', 'чернетка'), ('confirmed', 'підтверджено')], max_length=16, verbose_name='у статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='дата й час зміни')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='trips.trip', verbose_name='рейс')),
            ],
            options={
                'verbose_name': 'запис журналу змін рейсу',
                'verbose_name_plural': 'журнал змін рейсів',
                'ordering': ['-changed_at'],
            },
        ),
    ]
