# Generated by Django 5.2.17 on 2026-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cargo_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='найменування вантажу'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_packaging',
            field=models.CharField(blank=True, max_length=100, verbose_name='вид пакування'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_unit',
            field=models.CharField(default='шт', max_length=20, verbose_name='одиниця виміру'),
        ),
        migrations.AddField(
            model_name='trip',
            name='places_count',
            field=models.PositiveIntegerField(default=1, verbose_name='кількість місць'),
        ),
    ]
